from tech_brief.agent.schemas import Digest


def render(digest: Digest) -> tuple[str, str]:
    """Return (subject, html) for the given digest."""
    subject = f"tech-brief for {digest.date}"

    parts: list[str] = [
        "<div style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px; margin: 0 auto; padding: 24px; color: #222;\">",
        f"<h1 style=\"font-size: 24px; margin-bottom: 8px;\">tech-brief for {_esc(digest.date)}</h1>",
        f"<p style=\"color: #555; margin-top: 0;\">{_esc(digest.overview)}</p>",
    ]

    for section in digest.topics:
        parts.append(
            f"<h2 style=\"font-size: 18px; margin-top: 32px; border-bottom: 1px solid #eee; padding-bottom: 4px;\">{_esc(section.topic)}</h2>"
        )
        parts.append("<ul style=\"padding-left: 20px;\">")
        for story in section.stories:
            parts.append(
                f'<li style="margin-bottom: 12px;">'
                f'<a href="{_esc(story.url)}" style="color: #0366d6; text-decoration: none;">{_esc(story.title)}</a>'
                f'<br/><span style="color: #666; font-size: 14px;">{_esc(story.one_liner)}</span>'
                f"</li>"
            )
        parts.append("</ul>")

    parts.append(
        '<hr style="margin-top: 40px; border: none; border-top: 1px solid #eee;"/>'
        '<p style="font-size: 12px; color: #999;">'
        'Generated by <a href="https://github.com/SammyBolger/tech-brief" style="color: #999;">tech-brief</a>.'
        "</p>"
    )
    parts.append("</div>")
    return subject, "\n".join(parts)


def _esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
